server:
  port: 8080
spring:
  sql:
    init:
      mode: embedded
  artemis:
    user: artemis
    password: simetraehcapa
    mode: native
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
jhajhria:
  brewery.:
    beer-inventory-service-host: http://localhost:8082

logging:
  level:
    com:
      jhajhria: debug